
const TermsAndConditions = () => {
  return (
    <div className='container'>
      <div className='border rounded-lg p-5 m-5'>
        <h1 className='text-3xl mb-3'>Terms and Conditions</h1>
        <p>Effective July 1st, 2024</p>
        General.2024
        These are Whizdeals.ca’s Terms of Use (“Terms”) that govern your use of the Whizdeal.ca platform, including its applications, websites, and other services linked to these Terms ("Services"). Please read these Terms carefully because they describe your rights and responsibilities and together with all other Terms and conditions referred to below regarding your use of Whizdeal.ca’s services. 
        What is Whizdeals.ca
        Whizdeals.ca is a free membership program and is wholly owned by Whizdeals.ca Inc. Whizdeals.ca Inc is incorporated under the laws of Ontario, Canada. Whizdeals.ca grants students access to exclusive discounts and offers from partner brands and service providers ("Partners") who promote their products and services on Whizdeals.ca’s platform. To access these discounts and offers, students must verify their student status through the platforms verification system (“Verification”). Non-student users with verifiable accounts may also access the platform.  Once verified, a user becomes a "Member" and gains access to the discounts and offers on the Whizdeals.ca platform. Users may also sign up on the platform as ‘Guests’ using their social media logins and Gmail logins. Such users will only access the platform for a maximum of 6 months, after which they are required to provide a verifiable student email address for continued access to the platform.
        The Services are provided by Whizdeals.ca Inc and its affiliates (collectively referred to as "Whizdeals.ca" "we," or "us"). Whether you are a signed-up Member or just browsing, these Terms apply to you. By using Whizdeals.ca’s Services, you fully accept and agree to these Terms. If you disagree with any part of these Terms, you must not use Whizdeals.ca. Please be sure to review the Terms periodically to ensure familiarity with the most current version.
        Account
        When you sign up on Whizdeals.ca with your membership account ("Account"), you confirm that you have reviewed and understood these Terms and Conditions. You agree to comply with them, including any future amendments. Additionally, you consent to Whizdeals.ca using and disclosing your personal information as detailed in the Whizdeals.ca Privacy Policy and subject to periodic updates. These Terms govern your use of the interactive websites, mobile and connected applications, software, and all other online interactive features and services, including but not limited to emails, newsletters, forums, communities, sweepstakes, and contests (collectively, the “Services”) operated by Whizdeals.ca and its subsidiaries (collectively, “Whizdeals.ca,” “we,” “us,” or “our”). You also promise that any information you submit to Whizdeals.ca is true, accurate, and complete, and you agree to maintain its accuracy at all times. You agree not to create an account for anyone other than yourself, impersonate another person, or falsify any aspect of Verification. Whizdeals.ca reserves the right to deny registration or Verification, or to cancel or suspend an account at any time if a violation of these Terms is detected or suspected.
        The Services are directed at students affiliated with post-secondary institutions in Canada. Whizdeals.ca complies with the Children’s Online Privacy Protection Act and does not permit registration by, and will not knowingly collect personally identifiable information from, anyone under 13. By registering for any Services, you represent and warrant that you are 13 years of age or older. You agree not to create an account on behalf of someone else, impersonate another person, or falsify any aspect of Verification.
        Each registration is intended for a single user only. You are not permitted to share your login credentials with others or allow anyone else to use your login details. You are responsible for keeping your password confidential and for any activities that occur under your account. Failing to comply with this will be considered a breach of these Terms, which may result in the immediate suspension or termination of your account. You agree to notify us immediately at support@whizdeals.ca. if you detect or suspect any unauthorized use of your password or account, or any other security breaches. Any fraudulent, abusive, or illegal activity may lead to the suspension or termination of your account at our discretion, and we may report such activity to law enforcement. You can terminate your account at any time by contacting us at support@whizdeals.ca.
        Access to the Site and Services
        Whizdeals.ca strives to allow access to the Site 24 hours a day, 7 days a week, apart from necessary maintenance operations and possible breakdowns. Whizdeals.ca is only bound by an obligation to make every effort to provide access to the Site and the Services and cannot be held responsible, and declines all responsibility, for any and all inaccessibility of the Site, interruption or temporary stoppage of Services. This could occur and would not be a violation of its contractual obligations under these Terms and Conditions or its legal obligations, in particular in Terms of the security of personal information, and this, whatever their nature (including without limitation computer viruses, unlawful intrusion into an automated data processing system, temporary stoppage of the service, etc.).
        Whizdeals.ca cannot guarantee the continuity of the Site, its permanence, or its compatibility with your operating system or your browser. You acknowledge that you are solely responsible for the proper functioning of your equipment.
        Please notify us immediately of any compromise or unauthorized use of your account by emailing support@Whizdeals.ca. We also have a Help and Support Center where security bulletins are posted. 
        Transfer of your Data to Third Parties
        We use your data to improve your experience. Our service means that we keep your data inside Whizdeals.ca unless we are required by law to disclose your data or you ask us or give us your permission to share it, for example:

        You ask us to or give us your permission to;
        To provide you with a discount or access to a partner’s platform; or
        If you agree to marketing emails and personalisation, to show you relevant messaging on your social media platforms, to let you know about Whizdeals.ca discounts we think you’ll enjoy.
        When we share your data outside Whizdeals.ca we will:
        Always share it in a secure way;
        Make sure it’s treated consistently with the Privacy and Cookie Policy
        If you have registered for a Whizdeals.ca account this will also allow you to login to third party partner websites and apps. To provide you with a seamless experience, it may be necessary to share your personal information with third party partner websites you choose to use your Whizdeals.ca login to access. We will only share what we need to in order to provide the service you are using and we will not share all of the data we hold about you.
        You accept our Privacy and Cookie Policy and agree that you will not do anything that shall compromise our compliance with the Privacy and Cookie Policy nor do anything contrary to the Privacy and Cookie Policy insofar as your use of the Site is concerned.
        We will only use your personal information as set out in our Privacy and Cookie Policy.
        We may amend the Privacy and Cookie Policy without notice and at our absolute discretion, and by continuing to use the Site you accept such changes.
        Links to third party websites
        Please note that where we provide links to third party websites, plug-ins and applications that are not affiliated with Whizdeals.ca such websites are out of our control and are not covered by this Policy. If you access third party websites using the links provided, the operators of these websites may collect information from you that could be used by them, in accordance with their own privacy policies. Please check these policies before you submit any personal information to these websites.
        Advertising Disclosure
        At Whizdeals.ca we generate commission from our commercial partners when you use your verified account to generate amazing offers and discounts. These partners may also pay us to help grow their brands. We may feature them on our social media channels, website and in our emails.
        Copyright Policy
        You may not post, distribute, perform, display, transmit or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. Whizdeals.ca has registered a designated agent under Canadian copyright law 
        If you believe that your work has been copied and posted on the Services in a way that constitutes copyright or trademark infringement, please notify the designated agent, Whizdeals.ca by email: support@Whizdeals.ca and insert “Terms of Use” in the subject line.
        A notification of claimed infringement must include the following:
        (a) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or trademark interest;
        (b) a description of the copyrighted work(s) or trademark(s) that you claim has been infringed;
        (c) a description of where the material that you claim is infringing is located on the Services (including any additional identifying information such as URLs and post numbers to assist us in identifying the allegedly infringing material);
        (d) your address, telephone number, and email address;
        (e) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or trademark owner, its agent, or the law; and
        (f) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright or trademark owner or authorized to act on the copyright or trademark owner’s behalf.
        If materials you have posted on the Services have been removed due to alleged infringement of a third party’s intellectual property rights, Whizdeals.ca will notify you. If you believe your materials have been wrongly removed, you may file a counter-notification containing the following:
        (a) an electronic or physical signature of the person authorized to act on your behalf;
        (b) a description of the material that has been removed or to which access has been disabled and where the material was located online before it was removed or access to it was disabled;
        (c) a written statement by you that under penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and
        (d) your address, telephone number, and email address; and
        (e) a statement that you consent to the jurisdiction of the court for the judicial district in which the address is located, or if your address is outside of the Canada, for any judicial district in which the service provider may be found.
        Upon Whizdeals.ca’ receipt of such counter-notice, Whizdeals.ca will provide the complainant with your contact information so that you have the ability to resolve the issue. Please note that when we forward the counter-notification, it includes your personal information. If you are concerned about protecting your anonymity, please consult with an attorney about other options. If the matter has been resolved or the complainant does not seek a court order within the statutory time period, we generally will re-post the material.
        Disclaimer of Warranties; Limitation of Liability
        Whizdeals.ca, along with its officers, directors, and employees, shall not be held liable for any issues arising from or connected to your use of Whizdeals.ca and its Services, regardless of whether the liability falls under contract, tort, or other legal frameworks. This includes any indirect, consequential, or special liabilities related to your use of Whizdeals.ca and its Services
        The Services and the Content are distributed on an “as is, as available” basis. None of Whizdeals.ca, third party vendors or content providers or their respective agents makes any warranties of any kind, either express or implied, including, without limitation, warranties of title or implied warranties of merchantability or fitness for a particular purpose, with respect to the Services, any Content or any products or services sold through the Services. Neither Whizdeals.ca nor any third party content provider warrants that any files available for downloading through the Services will be free of viruses or similar contamination or destructive features. Neither Whizdeals.ca nor any third party content provider warrants that any of the goods or services linked to or advertised in the Services comply with data protection or other relevant legislation and Whizdeals.ca accepts no liability whatsoever for any claim arising from such goods or services.
        You expressly agree that the entire risk as to the quality and performance of the Services and the accuracy or completeness of the Content is assumed solely by you and Whizdeals.ca cannot guarantee the continued availability of any particular component of the Services. You specifically acknowledge that Whizdeals.ca is not responsible or liable for any unauthorized access to or alteration of your materials, data or other transmissions entered into through the Services or for any threatening, defamatory, obscene, offensive or illegal Content or for conduct of any other party or for any infringement of another’s rights.
        10.Indemnification
        You hereby agree to indemnify Whizdeals.ca from and against any and all liabilities, costs, demands, causes of action, damages and expenses arising out of or in any way related to your breach of any of the provisions of these Terms.
        11.Severability
        If any provision of these Terms is found to be unenforceable or invalid under any applicable law, such unenforceability or invalidity shall not render these Terms unenforceable or invalid as a whole, and such provisions shall be deleted without affecting the remaining provisions herein.
        12.Amendments to the Terms
        Whizdeals.ca reserves the right to make changes to any of our services, policies, including these Terms, at any time. You will be subject to the Terms at the time that you use Whizdeals.ca and the Services. If any of the conditions in these Terms is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.
        13.Entire Agreement
        These Terms, including any legal notices and disclaimers contained on this Website, constitute the entire agreement between Whizdeals.ca and you in relation to your use of Whizdeals.ca and the Services and supersede all prior agreements and understandings with respect to the same.
      </div>
    </div>
  )
}

export default TermsAndConditions
